version: '3.1'

networks:
  net_hyper42:
    external: true

services:
  backend:
     image: registry.hyperport.nl:5000/kim-backend:kim-offchain_1.0.0-SNAPSHOT
     container_name: "kim-backend"
     volumes:
      - ../blockchain-platform/bc-network/crypto-config:/crypto-config
     ports:
       - 7080:7080
     networks:
      - net_hyper42
