# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.org3.hyper42.nl:
  peer1.org3.hyper42.nl:

networks:
  hyper42:

services:

  peer0.org3.hyper42.nl:
    container_name: peer0.org3.hyper42.nl
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.hyper42.nl
      - CORE_PEER_ADDRESS=peer0.org3.hyper42.nl:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.hyper42.nl:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.hyper42.nl/peers/peer0.org3.hyper42.nl/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.hyper42.nl/peers/peer0.org3.hyper42.nl/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.hyper42.nl:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - hyper42

  peer1.org3.hyper42.nl:
    container_name: peer1.org3.hyper42.nl
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.hyper42.nl
      - CORE_PEER_ADDRESS=peer1.org3.hyper42.nl:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.hyper42.nl:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.hyper42.nl:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.hyper42.nl/peers/peer1.org3.hyper42.nl/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/org3.hyper42.nl/peers/peer1.org3.hyper42.nl/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.hyper42.nl:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - hyper42


  Org3cli:
    container_name: Org3cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=Org3cli
      - CORE_PEER_ADDRESS=peer0.org3.hyper42.nl:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyper42.nl/peers/peer0.org3.hyper42.nl/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyper42.nl/peers/peer0.org3.hyper42.nl/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyper42.nl/peers/peer0.org3.hyper42.nl/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.hyper42.nl/users/Admin@org3.hyper42.nl/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org3-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/org1.hyper42.nl:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.hyper42.nl
        - ./crypto-config/peerOrganizations/org2.hyper42.nl:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.hyper42.nl
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.org3.hyper42.nl
      - peer1.org3.hyper42.nl
    networks:
      - hyper42
